authapp/urls.py
from django.urls import path
from .views import register, edit, verify, UserLoginView, UserLogoutView
# from .views import login, logout

app_name = 'authapp'
urlpatterns = [
    # path('login/', login, name='login'),
    path('login/', UserLoginView.as_view(), name='login'),
    # path('logout/', logout, name='logout'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify'),
]

basketapp/urls.py
from django.urls import path
from .views import basket, basket_add, basket_remove, basket_edit

app_name = 'basketapp'
urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>)/', basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit'),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

from geekshop.views import index, contacts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('mainapp.urls', namespace='products'), name='products'),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff'), name='admin_staff'),
    path('auth/', include('authapp.urls', namespace='auth'), name='auth'),
    path('basket/', include('basketapp.urls', namespace='basket'), name='basket'),
    path('order/', include('ordersapp.urls', namespace='order'), name='order'),
    path('contacts/', contacts, name='contacts'),
    path('', index, name='index'),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import path
from .views import products, product, products_ajax
from django.views.decorators.cache import cache_page

app_name = 'mainapp'
urlpatterns = [
    path('', products, name='index'),
    path('category/<int:pk>/', products, name='category'),
    path(
        'category/<int:pk>/ajax/',
         cache_page(3600)(products_ajax),
         name='ajax_category'
    ),
    path(
        'category/<int:pk>/page/<int:page>/',
        # cache_page(3600)(products),  # controller caching
        products,
        name='page'
    ),
    path(
        'category/<int:pk>/page/<int:page>/ajax/',
        cache_page(3600)(products_ajax),
        name='ajax_page'
    ),
    path('product/<int:pk>/', product, name='product')
]

mainapp/models.py
from django.db import models


# Create your models here.
class ProductCategory(models.Model):
    name = models.CharField(
        verbose_name='имя',
        max_length=64,
        unique=True,
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )
    is_active = models.BooleanField(
        db_index=True,
        default=True,
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
    )
    updated_at = models.DateTimeField(
        auto_now=True,
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'категория'
        verbose_name_plural = 'категории'

    def soft_delete(self):
        self.is_active = False
        self.save()


class Product(models.Model):
    category = models.ForeignKey(
        ProductCategory,
        on_delete=models.CASCADE,
        verbose_name='категория',
    )
    name = models.CharField(
        verbose_name='название',
        max_length=128,
    )
    short_desc = models.CharField(
        verbose_name='краткое описание',
        max_length=256,
        blank=True,
    )
    image = models.ImageField(
        upload_to='product_images',
        blank=True,
    )
    description = models.TextField(
        verbose_name='описание',
        blank=True,
    )
    price = models.DecimalField(
        verbose_name='цена',
        max_digits=8,
        decimal_places=2,
        default=0,
    )
    quantity = models.PositiveIntegerField(
        verbose_name='количество на складе',
        default=0,
    )
    is_active = models.BooleanField(
        db_index=True,
        default=True,
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
    )
    updated_at = models.DateTimeField(
        auto_now=True,
    )

    def soft_delete(self):
        self.is_active = False
        self.save()

    def __str__(self):
        return '%s - %s' % (self.name, self.pk)

    class Meta:
        verbose_name = 'товар'
        verbose_name_plural = 'товары'

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

mainapp/views.py
import random
from django.shortcuts import render, get_object_or_404
# from json import loads
# from basketapp.models import Basket
from mainapp.models import Product, ProductCategory
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.conf import settings
from django.core.cache import cache
from django.template.loader import render_to_string
from django.http import JsonResponse


# def get_basket(user):  # basket now from context processor
#     if user.is_authenticated:
#         return Basket.objects.filter(user=user)
#     return []

def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links.menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():  # Alternative variant of function logic (more DRY)
    if settings.LOW_CACHE:  # if cache activated, try to find product in it
        key = 'products'
        products = cache.get(key)
    else:
        products = None
    if products is None:  # if cache not active or product not found
        products = Product.objects.filter(
            is_active=True,
            category__is_active=True,
        ).select_related('category')
        if settings.LOW_CACHE:  # if cache active, put product in cache
            cache.set(key, products)
    return products


def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        product = cache.get(key)
        if product is None:
            product = get_object_or_404(Product, pk=pk)
            cache.set(key, product)
        return product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_ordered_by_price():  # Alternative variant of function logic
    if settings.LOW_CACHE:  # if cache activated, try to find product in it
        key = 'products_ordered_by_price'
        products = cache.get(key)
    else:
        products = None
    if products is None:  # if cache not active or product not found
        products = Product.objects.filter(
            is_active=True,
            category__is_active=True,
        ).order_by('price')
        if settings.LOW_CACHE:  # if cache active, put product in cache
            cache.set(key, products)
    return products


def get_products_in_category_ordered_by_price(pk):  # Alternative variant logic
    if settings.LOW_CACHE:  # if cache activated, try to find product in it
        key = 'products_in_category_ordered_by_price'
        products = cache.get(key)
    else:
        products = None
    if products is None:  # if cache not active or product not found
        products = Product.objects.filter(
            category__pk=pk,
            is_active=True,
            category__is_active=True,
        ).order_by('price')
        if settings.LOW_CACHE:  # if cache active, put product in cache
            cache.set(key, products)
    return products


def get_hot_product():
    # hot_query = Product.objects.filter(
    #     is_active=True,
    #     category__is_active=True
    # )  # code without caching func
    hot_query = get_products()  # with caching
    # if len(list(hot_query)) <= 0:
    #     return []
    return random.sample(list(hot_query), 1)[0]


def get_related_products(product):
    related_products = Product.objects\
            .filter(is_active=True, category__is_active=True)\
            .select_related('category')\
            .exclude(pk=product.pk)[:3]
    return related_products


def products(request, pk=None, page=1):
    title = 'продукты'
    # menu_links = ProductCategory.objects.filter(is_active=True) #  w/o cache
    menu_links = get_links_menu()
    # basket = get_basket(request.user)
    hot_product = get_hot_product()
    related_products = get_related_products(hot_product)

    if pk is not None:
        if pk == 0:
            # without cache
            # products = Product.objects.filter(
            #    is_active=True,
            #    category__is_active=True
            # ).order_by('price')
            products = get_products_ordered_by_price()  # with cache
            category = {
                'name': 'все',
                'pk': 0
            }
        else:
            # without cache
            # category = get_object_or_404(ProductCategory, pk=pk)
            # products = Product.objects.filter(
            #    category__pk=pk,
            #    is_active=True,
            #    category__is_active=True
            # ).order_by('price')  # without cache
            # with cache
            category = get_category(pk)
            products = get_products_in_category_ordered_by_price(pk)

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        context = {
            'title': title,
            'menu_links': menu_links,
            'related_products': related_products,
            'category': category,
            'products': products_paginator,
            # 'basket': basket,
            'hot_product': hot_product,
        }
        return render(request, 'mainapp/products.html', context)

    category = {
        'name': 'все',
        'pk': 0
    }
    # without cache
    # products = Product.objects.filter(is_active=True).order_by('price')
    products = get_products_ordered_by_price()  # with cache
    paginator = Paginator(products, 2)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    context = {
        'title': title,
        'menu_links': menu_links,
        'related_products': related_products,
        'category': category,
        'products': products_paginator,
        # 'basket': basket,
        'hot_product': hot_product,
    }
    return render(request, 'mainapp/products.html', context)


def products_ajax(request, pk=None, page=1):
    if request.is_ajax():
        menu_links = get_links_menu()
        hot_product = get_hot_product()
        related_products = get_related_products(hot_product)
        if pk is None or pk == 0:
            products = get_products_ordered_by_price()
            category = {
                'name': 'все',
                'pk': 0
            }
        else:
            category = get_category(pk)
            products = get_products_in_category_ordered_by_price(pk)

        paginator = Paginator(products, 2)
        try:
            products_paginator = paginator.page(page)
        except PageNotAnInteger:
            products_paginator = paginator.page(1)
        except EmptyPage:
            products_paginator = paginator.page(paginator.num_pages)

        context = {
            'menu_links': menu_links,
            'category': category,
            'products': products_paginator,
            'related_products': related_products,
            'hot_product': hot_product,
        }
        result = render_to_string(
            'mainapp/includes/inc_products_list_content.html',
            context=context,
            request=request
        )
        return JsonResponse({'result': result})


def product(request, pk):
    title = 'продукты'
    # without cache
    # menu_links = ProductCategory.objects.filter(is_active=True)
    menu_links = get_links_menu()  # with cache
    # basket = get_basket(request.user)
    # product = get_object_or_404(Product, pk=pk)  # without cache
    product = get_product(pk)
    related_products = get_related_products(product)
    context = {
        'title': title,
        'menu_links': menu_links,
        'related_products': related_products,
        # 'basket': basket,
        'product': product,
    }
    return render(request, 'mainapp/product.html', context)

mainapp/templates/mainapp/includes/inc_cat_menu.html
<div class="links clearfix">
    <ul class="links-menu">
        <li>
            <a href="{% url 'products:category' 0 %}"
               class="{% if request.resolver_match.kwargs.pk == 0 %}active
                      {% endif %}">
                все
            </a>
        </li>
        {% for link in menu_links %}
            <li>
                <a href="{% url 'products:category' link.pk %}"
                   class="{% if request.resolver_match.kwargs.pk|add:'0' == link.pk %}active
                          {% endif %}">
                   {{ link.name }}
                </a>
            </li>
        {% endfor %}
    </ul>
</div>

mainapp/templates/mainapp/includes/inc_products_list_content.html
{% load static %}
{% load newtags %}
    <div class="details">
        {% include 'mainapp/includes/inc_cat_menu.html' %}
        <div class="details-products">
            <div class="details-slider">
                <div class="slider-product">
                    <img src="{{ hot_product.image|prod_img_path }}">
                </div>
                <div class="slider-control">
                    <div class="block">
                        <a href="#"><img src="{{ hot_product.image|prod_img_path }}" style="width:70px;" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{{ hot_product.image|prod_img_path }}" style="width:70px;" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                    <div class="block">
                        <a href="#"><img src="{{ hot_product.image|prod_img_path }}" style="width:70px;" alt="">
                            <div class="text"></div>
                        </a>
                    </div>
                </div>
            </div>

            <div class="description">
                <h3 class="big-bold">{{ hot_product.name }}</h3>
                <h3 class="red">горячее предложение</h3>
                <p class="price"> {{ hot_product.price }} <span>руб</span></p>
                <a href="{% url 'basket:add' hot_product.pk %}" class="red-button">
                    заказать <i class="fa fa-chevron-right" aria-hidden="true"></i>
                </a>
                <div class="description-text">
                    <p>{{ hot_product.description }}</p>
                </div>
            </div>
        </div>

        <div class="related">
            {% if category %}
            <div class="title clearfix">
                <h2>
                    Категория: {{ category.name|title }}
                </h2>
            </div>
            {% endif %}
            <div class="related-products clearfix">
                {% for item in products %}
                <div class="block">
                    <a href="{% url 'products:product' item.pk %}">
                        <img src="{{ item.image|prod_img_path }}" alt="product">
                        <div class="text">
                            <img src="{% static 'geekshop/img/icon-hover.png' %}" alt="hover">
                            <h4>{{ item.name }}</h4>
                            <p>{{ item.short_desc }}</p>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
            <div class="paginator">
                {% if products.has_previous %}
                    <a href="{% url 'products:page' category.pk products.previous_page_number %}">
                        <
                    </a>
                {% endif %}
            <span class="current">
                страница {{ products.number }} из
                {{ products.paginator.num_pages }}
            </span>
                {% if products.has_next %}
                    <a href="{% url 'products:page' category.pk products.next_page_number %}">
                        >
                    </a>
                {% endif %}
            </div>
        </div>


        <div class="related">
            <div class="title clearfix">
                <h2>Похожие продукты</h2>
                <a class="explore" href="#">показать все <img src="{% static 'geekshop/img/arrow.png' %}" alt=""></a>
            </div>
            <div class="related-products clearfix">
                {% for item in related_products %}
                <div class="block">
                    <a href="#"><img src="{{ item.image|prod_img_path }}" alt="">
                        <div class="text">
                            <img src="{% static 'geekshop/img/icon-hover.png' %}" alt="img">
                            <h4>{{ item.name }}</h4>
                            <p>{{ item.short_desc }}</p>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>