adminapp/urls.py
from django.urls import path
from adminapp.views import (
    # users,
    # user_create,
    # user_update,
    # user_delete,
    # categories,
    # category_create,
    # category_update,
    # category_delete,
    # products,
    # product_create,
    # product_read,
    # product_update,
    # product_delete,
    UserListView,
    UserCreateView,
    ProductDetailView,
    UserUpdateView,
    UserDeleteView,
    CategoryListView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    ProductListView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
)

app_name = 'adminapp'
urlpatterns = [
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    path('users/read/', UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),

    path('categories/read/', CategoryListView.as_view(), name='categories'),
    path('categories/create/', CategoryCreateView.as_view(), name='category_create'),
    path('categories/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),

    path('products/read/category/<int:pk>/', ProductListView.as_view(), name='products'),
    path('products/create/category/<int:pk>/', ProductCreateView.as_view(), name='product_create'),
    path('products/read/<int:pk>/', ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
]

authapp/urls.py
from django.urls import path
from .views import register, edit, verify, UserLoginView, UserLogoutView
# from .views import login, logout

app_name = 'authapp'
urlpatterns = [
    # path('login/', login, name='login'),
    path('login/', UserLoginView.as_view(), name='login'),
    # path('logout/', logout, name='logout'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify'),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

from geekshop.views import index, contacts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('mainapp.urls', namespace='products'), name='products'),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff'), name='admin_staff'),
    path('auth/', include('authapp.urls', namespace='auth'), name='auth'),
    path('basket/', include('basketapp.urls', namespace='basket'), name='basket'),
    path('order/', include('ordersapp.urls', namespace='order'), name='order'),
    path('contacts/', contacts, name='contacts'),
    path('', index, name='index'),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

adminapp/models.py
from django.db import models

# Create your models here.

adminapp/forms.py
from django import forms
from mainapp.models import ProductCategory, Product


class ProductCategoryEditForm(forms.ModelForm):
    discount = forms.IntegerField(
        label='скидка',
        required=False,
        min_value=0,
        max_value=90,
        initial=0
    )

    class Meta:
        model = ProductCategory
        fields = ('name', 'description')
        # fields = '__all__'
        exclude = ()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''


class ProductEditForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        exclude = ('is_active',)

    def __init__(self, *args, **kwargs):
        super(ProductEditForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
            field.help_text = ''

adminapp/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from adminapp.forms import ProductCategoryEditForm, ProductEditForm
from authapp.forms import ShopUserRegisterForm
from authapp.models import ShopUser
from mainapp.models import ProductCategory, Product
from django.views.generic import ListView, CreateView, DetailView,\
    UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.dispatch import receiver
from django.db import connection
from django.db.models.signals import pre_save
from django.db.models import F, Q
import os


def db_profile_by_type(prefix, type, queries):
    LOG_PATH = 'tmp/logs'
    update_queries = list(filter(lambda x: type in x['sql'], queries))
    with open(os.path.join(LOG_PATH, 'log.txt'), 'a', encoding='utf-8') as log:
        log.write(f'db_profile {type} for {prefix}:\n')
        [log.write(query['sql'] + '\n') for query in update_queries]


class UserListView(LoginRequiredMixin, ListView):
    model = ShopUser
    template_name = 'adminapp/users.html'
    context_object_name = 'user_list'
    ordering = ['-is_active', '-is_superuser', '-is_staff', 'username']

    def get_context_data(self, **kwargs):
        context = super(UserListView, self).get_context_data(**kwargs)
        title = 'Пользователи'
        context.update({'title': title})
        return context


class UserCreateView(LoginRequiredMixin, CreateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    success_url = reverse_lazy('admin_staff:users')
    form_class = ShopUserRegisterForm

    def get_context_data(self, **kwargs):
        context = super(UserCreateView, self).get_context_data(**kwargs)
        title = 'Создать пользователя'
        context.update({'title': title})
        return context


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = ShopUser
    template_name = 'adminapp/user_update.html'
    form_class = ShopUserRegisterForm
    success_url = reverse_lazy('admin_staff:users')

    def get_context_data(self, **kwargs):
        context = super(UserUpdateView, self).get_context_data(**kwargs)
        title = 'Редактировать пользователя'
        context.update({'title': title})
        return context


class UserDeleteView(LoginRequiredMixin, DeleteView):
    model = ShopUser
    template_name = 'adminapp/user_delete.html'
    success_url = reverse_lazy('admin_staff:users')

    def get_context_data(self, **kwargs):
        context = super(UserDeleteView, self).get_context_data(**kwargs)
        title = 'удаление пользователя'
        context.update({'title': title})
        return context

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.soft_delete()
        return HttpResponseRedirect(self.get_success_url())


class CategoryListView(LoginRequiredMixin, ListView):
    model = ProductCategory
    template_name = 'adminapp/categories.html'
    context_object_name = 'categories'
    ordering = ['-is_active', 'name']

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        title = 'Категории товаров'
        context.update({'title': title})
        return context


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin_staff:categories')
    form_class = ProductCategoryEditForm

    def get_context_data(self, **kwargs):
        context = super(CategoryCreateView, self).get_context_data(**kwargs)
        title = 'Создать категорию'
        context.update({'title': title})
        return context


class CategoryUpdateView(LoginRequiredMixin, UpdateView):
    model = ProductCategory
    template_name = 'adminapp/category_update.html'
    success_url = reverse_lazy('admin_staff:categories')
    form_class = ProductCategoryEditForm

    def get_context_data(self, **kwargs):
        context = super(CategoryUpdateView, self).get_context_data(**kwargs)
        title = 'Редактировать категорию'
        context.update({'title': title})
        return context

    def form_valid(self, form):
        if 'discount' in form.cleaned_data:
            discount = form.cleaned_data['discount']
            if discount:
                self.object.product_set\
                        .update(price=F('price') * (1 - discount / 100))
                db_profile_by_type(
                    self.__class__,
                    'UPDATE',
                    connection.queries
                )
        return super().form_valid(form)


class CategoryDeleteView(LoginRequiredMixin, DeleteView):
    model = ProductCategory
    template_name = 'adminapp/category_delete.html'
    success_url = reverse_lazy('admin_staff:categories')

    def get_context_data(self, **kwargs):
        context = super(CategoryDeleteView, self).get_context_data(**kwargs)
        title = 'удаление категории'
        context.update({'title': title})
        return context

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.soft_delete()
        return HttpResponseRedirect(self.get_success_url())


class ProductListView(LoginRequiredMixin, ListView):
    model = Product
    template_name = 'adminapp/products.html'
    context_object_name = 'products'

    def get_queryset(self, **kwargs):
        return Product.objects.filter(category__id=self.kwargs['pk'])\
            .order_by('name')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        title = 'Товары'
        category = get_object_or_404(ProductCategory, pk=self.kwargs['pk'])
        context.update({'title': title, 'category': category})
        return context


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    template_name = 'adminapp/product_update.html'
    form_class = ProductEditForm

    def get_context_data(self, **kwargs):
        context = super(ProductCreateView, self).get_context_data(**kwargs)
        title = 'Создание товара'
        category = get_object_or_404(ProductCategory, pk=self.kwargs['pk'])
        context.update({'title': title, 'category': category})
        return context

    def get_success_url(self):
        category_id = self.kwargs['pk']
        return reverse_lazy('admin_staff:products', kwargs={'pk': category_id})


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product
    template_name = 'adminapp/product_read.html'


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    template_name = 'adminapp/product_update.html'
    form_class = ProductEditForm

    def get_context_data(self, **kwargs):
        context = super(ProductUpdateView, self).get_context_data(**kwargs)
        title = 'Редактирование товара'
        category = get_object_or_404(Product, pk=self.kwargs['pk']).category
        context.update({'title': title, 'category': category})
        return context

    def get_success_url(self):
        category_id = self.kwargs['pk']
        return reverse_lazy('admin_staff:products', kwargs={'pk': category_id})


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    template_name = 'adminapp/product_delete.html'
    context_object_name = 'product_to_del'

    def get_context_data(self, **kwargs):
        context = super(ProductDeleteView, self).get_context_data(**kwargs)
        title = 'удаление товара'
        context.update({'title': title})
        return context

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.soft_delete()
        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        product_pk = self.kwargs['pk']
        category_pk = get_object_or_404(Product, pk=product_pk).category.pk
        return reverse_lazy('admin_staff:products', kwargs={'pk': category_pk})


@receiver(pre_save, sender=ProductCategory)
def product_is_active_update_productcategory_save(sender, instance, **kwargs):
    if instance.pk:
        if instance.is_active:
            instance.product_set.update(is_active=True)
        else:
            instance.product_set.update(is_active=False)
        db_profile_by_type(sender, 'UPDATE', connection.queries)

adminapp/templates/adminapp/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <title>
        {% block title %}
        {{ title|title }}
        {% endblock %}
    </title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'geekshop/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'adminapp/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'geekshop/fonts/font-awesome/css/font-awesome.css' %}">
    <link href='https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css' rel='stylesheet'>

    {% block css %}
    {% endblock %}

    <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js'></script>
    <script src="{% static 'adminapp/js/admin_script.js' %}"></script>
    {% block js %}
    {% endblock %}
</head>
<body id="body-pd">
<header class="header" id="header">
    <div class="header_toggle"><i class='bx bx-menu' id="header-toggle"></i></div>
    <div class="header_img"><img src="/media/{{ user.avatar }}" alt=""></div>
</header>
<div class="l-navbar" id="nav-bar">
    <nav class="nav">
        <div><a href="{% url 'index' %}" class="nav_logo">
            <i class='bx bx-layer nav_logo-icon'></i>
            <span class="nav_logo-name">Administration</span>
        </a>
            <div class="nav_list">
                {% include 'adminapp/includes/inc_menu.html' %}
            </div>
        </div>
        <a href="{% url 'auth:logout' %}" class="nav_link">
            <i class='bx bx-log-out nav_icon'></i>
            <span class="nav_name">Выход</span>
        </a>
    </nav>
</div>
<!--Container Main start-->
<div class="height-100 bg-light">
    {% block content %}
    {% endblock %}
</div>
<!--Container Main end-->
</body>
</html>

adminapp/templates/adminapp/categories.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Управление категориями товаров</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Категории
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Категория</th>
                            <th>Описание</th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Категория</th>
                            <th>Описание</th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for category in categories %}
                            <tr style="{% if not category.is_active %}opacity: .3;{% endif %}">
                                <td>{{ category.name|title }}</td>
                                <td>{{ category.description }}</td>
                                <td class="text-center">
                                    {% if category.is_active %}
                                        <button type="button" class="btn btn-info">
                                            <a href="{% url 'admin_staff:products' category.pk %}">
                                                товары категории
                                            </a>
                                        </button>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {% if category.is_active %}
                                        <button type="button" class="btn btn-info">
                                            <a href="{% url 'admin_staff:category_update' category.pk %}">
                                                редактировать
                                            </a>
                                        </button>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {% if category.is_active %}
                                        <button type="button" class="btn btn-warning">
                                            <a href="{% url 'admin_staff:category_delete' category.pk %}">
                                                удалить
                                            </a>
                                        </button>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'admin_staff:category_create' %}">
                    <button class="btn btn-success">Создать категорию</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/category_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">{{ title|title }}</h1>
        <div class="card mb-4">
            <div class="card-header">
            </div>
            <div class="card-body">
                Уверены, что хотите удалить {{ object.name }}?
                <form method="POST">
                    {% csrf_token %}
                    <input class="btn btn-danger" type="submit" value="удалить">
                    <button class="btn btn-success">
                        <a href="{% url 'admin_staff:categories' %}">
                            Отмена
                        </a>
                    </button>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/category_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">{{ title|title }}</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Категория
            </div>
            <div class="card-body">
                <form class="form-horizontal" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="form-control btn-success" type="submit" value="сохранить">
                </form>
            </div>
        </div>
        <button class="btn btn-info">
            <a href="{% url 'admin_staff:categories' %}">
                К категориям
            </a>
        </button>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/product_delete.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">{{ title|title }}</h1>
        <div class="card mb-4">
            <div class="card-header">
            </div>
            <div class="card-body">
                Уверены, что хотите удалить {{ product_to_del.name }}?
                <form  method="post">
                    {% csrf_token %}
                    <input class="btn btn-danger" type="submit" value="удалить">
                    <button class="btn btn-success">
                        <a href="{% url 'admin_staff:products' product_to_del.category.pk %}">
                            Отмена
                        </a>
                    </button>
                </form>
            </div>
        </div>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/product_read.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load newtags %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">{{ title|title }}</h1>
        <div class="card mb-4">
            <div class="card-body">
                <div class="details-slider">
                    <img src="{{ product.image|prod_img_path }}">
                </div>

                <h3 class="big-bold">{{ product.name }}</h3>
                <p class="price"> {{ product.price }} <span>руб</span></p>
                <p>Количество: {{ product.quantity }}</p>
                <div class="description-text">
                    <p>{{ product.short_desc }}</p>
                    <hr>
                    <p>{{ product.description }}</p>
                </div>
            </div>
        </div>
        <button class="btn btn-info">
            <a href="{% url 'admin_staff:products' product.category.pk %}">
                к списку товаров
            </a>
        </button>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/product_update.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">{{ title|title }}</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Редактирование/Создание
            </div>
            <div class="card-body">
                <form  method="post">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <input class="form-control btn-success" type="submit" value="сохранить">
                </form>
            </div>
        </div>
        <button class="btn btn-info">
            <a href="{% url 'admin_staff:products' category.pk %}">
                к списку  товаров
            </a>
        </button>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/products.html
{% extends 'adminapp/base.html' %}
{% load static %}
{% load newtags %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Товары</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                {{ category.name|title }}
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Изображение</th>
                            <th>Название</th>
                            <th>Краткое описание</th>
                            <th>Цена</th>
                            <th>Количество</th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Изображение</th>
                            <th>Название</th>
                            <th>Краткое описание</th>
                            <th>Цена</th>
                            <th>Количество</th>
                            <th></th>
                            <th></th>
                            <th></th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for product in products %}
                            <tr style="{% if not product.is_active %}opacity: .3;{% endif %}">
                                <td><img src="{{ product.image|prod_img_path }}" width="120px"></td>
                                <td>{{ product.name }}</td>
                                <td>{{ product.short_desc }}</td>
                                <td>{{ product.price }}</td>
                                <td>{{ product.quantity }}</td>
                                <td class="text-center">
                                    {% if product.is_active %}
                                        <button type="button" class="btn btn-info">
                                            <a href="{% url 'admin_staff:product_read' product.pk %}">
                                                Подробнее
                                            </a>
                                        </button>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {% if product.is_active %}
                                        <button type="button" class="btn btn-info">
                                            <a href="{% url 'admin_staff:product_update' product.pk %}">
                                                Редактировать
                                            </a>
                                        </button>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {% if product.is_active %}
                                        <button type="button" class="btn btn-warning">
                                            <a href="{% url 'admin_staff:product_delete' product.pk %}">
                                                Удалить
                                            </a>
                                        </button>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:product_create' category.pk %}">
                    <button class="btn btn-success">Создать товар</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}

adminapp/templates/adminapp/users.html
{% extends 'adminapp/base.html' %}
{% load static %}

{% block content %}
<main>
    <div class="container-fluid">
        <h1 class="mt-4">Пользователи</h1>
        <div class="card mb-4">
            <div class="card-header">
                <i class="fas fa-table mr-1"></i>
                Список
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                        <thead>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Адрес эл. почты</th>
                            <th class="text-center">Персонал сайта</th>
                            <th class="text-center">Активный</th>
                            <th></th>
                        </tr>
                        </thead>
                        <tfoot>
                        <tr>
                            <th>Имя пользователя</th>
                            <th>Имя</th>
                            <th>Адрес эл. почты</th>
                            <th class="text-center">Персонал сайта</th>
                            <th class="text-center">Активный</th>
                            <th></th>
                        </tr>
                        </tfoot>
                        <tbody>
                        {% for user in user_list %}
                            <tr style="{% if not user.is_active %}opacity: .3;{% endif %}">
                                <td>
                                    {% if user.is_active %}
                                        <a href="{% url 'admin_staff:user_update' user.id %}" style="color: dodgerblue">
                                            {{ user.username }}
                                        </a>
                                    {% else %}
                                        {{ user.username }}
                                    {% endif %}
                                </td>
                                <td>{{ user.first_name }}</td>
                                <td>{{ user.email }}</td>
                                <td class="text-center">
                                    {% if user.is_staff %}
                                        <i class="fa fa-check-circle"></i>
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {% if user.is_active %}
                                        <i class="fa fa-check-circle"></i>
                                    {% else %}
                                        <i class="fa fa-times-circle"></i>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    {% if user.is_active %}
                                        <button type="button" class="btn btn-warning">
                                            <a href="{% url 'admin_staff:user_delete' user.pk %}">
                                                Удалить
                                            </a>
                                        </button>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'adminapp:user_create' %}">
                    <button class="btn btn-success">Создать пользователя</button>
                </a>
            </div>
        </div>
    </div>
</main>
{% endblock %}