adminapp/urls.py
from django.urls import path
from adminapp.views import (
    # users,
    # user_create,
    # user_update,
    # user_delete,
    # categories,
    # category_create,
    # category_update,
    # category_delete,
    # products,
    # product_create,
    # product_read,
    # product_update,
    # product_delete,
    UserListView,
    UserCreateView,
    ProductDetailView,
    UserUpdateView,
    UserDeleteView,
    CategoryListView,
    CategoryCreateView,
    CategoryUpdateView,
    CategoryDeleteView,
    ProductListView,
    ProductCreateView,
    ProductUpdateView,
    ProductDeleteView,
)

app_name = 'adminapp'
urlpatterns = [
    path('users/create/', UserCreateView.as_view(), name='user_create'),
    path('users/read/', UserListView.as_view(), name='users'),
    path('users/update/<int:pk>/', UserUpdateView.as_view(), name='user_update'),
    path('users/delete/<int:pk>/', UserDeleteView.as_view(), name='user_delete'),

    path('categories/read/', CategoryListView.as_view(), name='categories'),
    path('categories/create/', CategoryCreateView.as_view(), name='category_create'),
    path('categories/update/<int:pk>/', CategoryUpdateView.as_view(), name='category_update'),
    path('categories/delete/<int:pk>/', CategoryDeleteView.as_view(), name='category_delete'),

    path('products/read/category/<int:pk>/', ProductListView.as_view(), name='products'),
    path('products/create/category/<int:pk>/', ProductCreateView.as_view(), name='product_create'),
    path('products/read/<int:pk>/', ProductDetailView.as_view(), name='product_read'),
    path('products/update/<int:pk>/', ProductUpdateView.as_view(), name='product_update'),
    path('products/delete/<int:pk>/', ProductDeleteView.as_view(), name='product_delete'),
]

authapp/urls.py
from django.urls import path
from .views import register, edit, verify, UserLoginView, UserLogoutView
# from .views import login, logout

app_name = 'authapp'
urlpatterns = [
    # path('login/', login, name='login'),
    path('login/', UserLoginView.as_view(), name='login'),
    # path('logout/', logout, name='logout'),
    path('logout/', UserLogoutView.as_view(), name='logout'),
    path('register/', register, name='register'),
    path('edit/', edit, name='edit'),
    path('verify/<str:email>/<str:activation_key>/', verify, name='verify'),
]

basketapp/urls.py
from django.urls import path
from .views import basket, basket_add, basket_remove, basket_edit

app_name = 'basketapp'
urlpatterns = [
    path('', basket, name='view'),
    path('add/<int:pk>/', basket_add, name='add'),
    path('remove/<int:pk>)/', basket_remove, name='remove'),
    path('edit/<int:pk>/<int:quantity>/', basket_edit, name='edit'),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views

from geekshop.views import index, contacts

urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('mainapp.urls', namespace='products'), name='products'),
    path('admin_staff/', include('adminapp.urls', namespace='admin_staff'), name='admin_staff'),
    path('auth/', include('authapp.urls', namespace='auth'), name='auth'),
    path('basket/', include('basketapp.urls', namespace='basket'), name='basket'),
    path('order/', include('ordersapp.urls', namespace='order'), name='order'),
    path('contacts/', contacts, name='contacts'),
    path('', index, name='index'),
    path('', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    import debug_toolbar
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += [path('__debug__/', include(debug_toolbar.urls))]

geekshop/views.py
from django.shortcuts import render
# from basketapp.models import Basket
# from mainapp.views import get_basket


def index(request):
    title = 'главная'
    # basket = get_basket(request.user)
    # total = 0
    context = {
        'title': title,
        # 'basket': basket,
    }
    return render(request, 'geekshop/index.html', context)


def contacts(request):
    title = 'контакты'
    # basket = get_basket(request.user)
    # total = 0
    context = {
        'title': title,
        # 'basket': basket,
    }
    return render(request, 'geekshop/contact.html', context)

geekshop/templates/geekshop/includes/inc_main_menu.html
<div class="header clearfix">
    <a href="/" class="logo"></a>
    <ul class="menu">
        <li><a href="{% url 'index' %}" class="{% if title == 'главная' %}active{% endif %}">домой</a></li>
        <li><a href="{% url 'products:index' %}" class="{% if title == 'продукты' %}active{% endif %}">продукты</a></li>
        <li><a href="{% url 'contacts' %}" class="{% if title == 'контакты' %}active{% endif %}">контакты</a></li>
        {% if user.is_authenticated %}
        <li>
            <div class="dropdown">
                <a class="dropbtn" href="#">
                    {{ user.first_name|default:'Пользователь' }}
                </a>
                <div class="dropdown-content">
                    <a a href="{% url 'auth:edit' %}">
                        профиль
                    </a>
                    {% if user.is_superuser %}
                    <a href="/admin/">
                        admin
                    </a>
                    {% endif %}
                    {% if user.is_staff %}
                    <a href="{% url 'admin_staff:users' %}">
                        dashboard
                    </a>
                    {% endif %}
                    <a href="{% url 'auth:logout' %}">
                        выйти
                    </a>
                </div>
            </div>
        </li>
        {% else %}
        <li>
            <a href="{% url 'auth:login' %}">
                войти
            </a>
        </li>
        {% endif %}
    </ul>
    <a href="#" class="search"></a>
    {% if basket %}
        <a href="{% url 'basket:view' %}" class="basket">
            <span style="font-weight: 600;">
                {{ basket.0.total_quantity }}
            </span>
        </a>
    {% else %}
        <div class="basket">
        </div>
    {% endif %}

</div>